### ISSUE TITLE
Search functionality not working

### ISSUE THREAD

**Issue by gigamesh** [ethereum-optimism/community-hub#102]
The search box in the header is not working (at least not for most search terms). We should probably try fixing it or replacing it.

## Update to include description, motivation, estimated effort and complexity, and tags to related packages to add to Linear

**Description**
The search box in the header is not working (at least not for most search terms). We should probably try fixing it or replacing it.

**Motivation**
This is a UX pain because users would expect for the search bar to work like any other search bar. Instead, they must first experience that it doesn't work as expected, and then opt to use CTL+F

**Estimated effort and complexity**
* Effort: 3-8 (don't currently know what is causing the search bar to not work correctly)
* Complexity: 0

**Tags to related packages**
* nil

**Comment by platocrat** [comment]
@gigamesh I noticed this too. It def is a massive pain

**Comment by smartcontracts** [comment]
Looking into this...

**Comment by smartcontracts** [comment]
We could try to this algolia search box that the hardhat team put together: https://github.com/nomiclabs/hardhat/blob/767f68dee84d6a47cd40153a8ab8552f41a95d5e/docs/.vuepress/theme/components/AlgoliaSearchBox.vue

**Comment by smartcontracts** [comment]
I don't have the energy to figure out how to integrate this right now but I can't imagine it's immensely difficult. Maybe a half day project.

**Comment by gigamesh** [comment]
I could probably do it in the next couple weeks

**Comment by smartcontracts** [comment]
@gigamesh I reached out to https://docsearch.algolia.com/docs/what-is-docsearch/. I'll take care of this one.

**Comment by smartcontracts** [comment]
Search functionality works now. Woot.
