### ISSUE TITLE
Dead link in docs tutorials

### ISSUE THREAD

**Issue by bghughes** [ethereum-optimism/community-hub#108]
**Describe the bug**
This is a dead link found on this page: https://community.optimism.io/docs/resources/tutorials.html 
<img width="780" alt="Screen Shot 2021-05-17 at 3 26 45 PM" src="https://user-images.githubusercontent.com/32072172/118552246-4b99ac00-b724-11eb-947c-2b58e73dc729.png">

**Comment by platocrat** [comment]
@bghughes Thanks for catching this!
