### ISSUE TITLE
I need to speak to someone

### ISSUE THREAD

**Issue by cohbin** [ethereum-optimism/community-hub#113]
I accidentally sent crypto to an optimism mainet address and i need it back. The adress is 0x6032a735638dff9834976115394525baa353c9d5

It is $165.00 in ethereum and $45.00 in usdc. If someone could contact me at cohbinc@gmail.com i would deeply appreciate it.

**Comment by smartcontracts** [comment]
Hi, it seems like you've sent those funds to an Ethereum mainnet address, not an OE address: https://etherscan.io/address/0x6032a735638dff9834976115394525baa353c9d5. Do you have access to the private keys for this account on Ethereum?

**Comment by cohbin** [comment]
No i dont think so. It popped up as an address to use on my coinbase wallet
and i assumed that it would stay in my wallet. I had accidentally clucked
on optimism mainet instead of just mainet.

**Comment by smartcontracts** [comment]
You may have to reach out to the coinbase wallet team to get this figured out. I'm not sure where that wallet it came from. Either way, it does seem that the transfer was executed on Ethereum mainnet and not on the Optimistic Ethereum mainnet. You can see this because the mainnet address has funds:
https://etherscan.io/address/0x6032a735638dff9834976115394525baa353c9d5

But there are no funds on L2:
https://optimistic.etherscan.io/address/0x6032a735638dff9834976115394525baa353c9d5

**Comment by smartcontracts** [comment]
I would recommend reaching out to the coinbase wallet team. If you are having difficulties getting in touch with the team, I can also try to reach out myself and see if this was a bug related to the OE integration. Sorry for the trouble.

**Comment by cohbin** [comment]
Yeah i tried reaching out a couple days ago to coinbase but i havent heard
back. I would really appreciate your help if it isnt too much trouble.

**Comment by cohbin** [comment]
I think i just found the key phrase. Im just not sure how to apply it to
get my funds back.

**Comment by cohbin** [comment]
You seem to be my only hope I've got of getting my money back...  i know
its not a whole lot of cash but it would help to have it. I wouldnt mind
throwing you some of it for helping me out.

**Comment by smartcontracts** [comment]
Please send me an email at kelvin DOT fichter AT [gmail] DOT com and I can attempt to help you further. No promises of course but I'll do my best.

**Comment by smartcontracts** [comment]
@cohbin I sent you an email. I'll do my best to help.

**Comment by smartcontracts** [comment]
I'm going to close this issue since it's not related to `community-hub` and I have a separate email thread with @cohbin trying to figure out how to get those funds back.

**Comment by smartcontracts** [comment]
Yay! After some further debugging @cohbin was able to get the funds back. So we can consider this one closed for real this time. 🎉🎉🎉
