### ISSUE TITLE
ติดตามการอัปเดต

### ISSUE THREAD

**Issue by OhArthits** [ethereum-optimism/community-hub#119]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

**Comment by smartcontracts** [comment]
Hi, I'm going to close this issue because it doesn't contain any information. Feel free to leave a comment or create another issue if you're having a particular problem.
