### ISSUE TITLE
Bridge tutorial feedback

### ISSUE THREAD

**Issue by bluemandegen** [ethereum-optimism/community-hub#124]
Extremely easy to follow tutorial.  Yes we like the memes; they fit at the bottom (outside of the meat and potatoes).

Extremely easy to switch networks, but I think that question will still come up because people don't read;

I would edit the intro paragraph as follows:  

The easiest way to move assets between Layer 1 and Layer 2 is to use the Optimism Gateway. You can make use of this gateway on any of our networks. **<--- click here for information on how to add any of the Optimism networks.**

**Comment by smartcontracts** [comment]
Thank you!! If you drop an ETH address I'll make you a hand drawn NFT :-)

**Comment by bluemandegen** [comment]
0x0D71d8a431D7E2965f01a78faf7FedD94de6750c

Good luck team optimism!

**Comment by smartcontracts** [comment]
Thank you! ❤️

**Comment by smartcontracts** [comment]
Thanks again for the review, here's my shitty drawing for you: https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/34765029840658706893803010833957019895695699803719888420488474708153190055937 :-)
