### ISSUE TITLE
Unable to view SNX transfered to Optimism net

### ISSUE THREAD

**Issue by dgodevais** [ethereum-optimism/community-hub#128]
**Describe the bug**
I made a deposit from mainnet to optimism net (https://gateway.optimism.io/) where I transfered 2.7 SNX coins. However, I do not see this value reflected in my metamask wallet. 

Here is the transaction:
https://etherscan.io/tx/0xd044a73ced39fc38f6c9535d5974662609650345fcf1d6e592a11de1c40ae21e

I was able to get the ETH deposit to work but not the SNX:

https://optimistic.etherscan.io/address/0x2d9bc3424ff1c4ec6d24d6219ddc781759870977

I would expect the SNX transaction to appear as well.

Any ideas on where to go from here would be very helpful. Thanks

**Comment by K-Ho** [comment]
Hey @dgodevais The L1 transaction you linked is only a "Approve" of SNX, but there is no deposit of SNX. Depositing requires two steps: First, an approval, and then a deposit, which will transfer your tokens into the bridge contract. You should be able to see that 2.7 SNX never left your L1 wallet in the first place :D

**Comment by smartcontracts** [comment]
@dgodevais Closing this issue unless you have any further questions!
