### ISSUE TITLE
Problem with transaction on MM

### ISSUE THREAD

**Issue by RushanKhannanov** [ethereum-optimism/community-hub#135]
I have connected the Optimistic Ethereum network on my Metamask.

Then I transferred ETH to this wallet. I made a swap and wanted to send the remaining ETH to another wallet.

On another wallet, I also connected the Optmistic Ethereum network.

I have a problem.
I have connected the Optimistic Ethereum network on my Metamask.

Then I transferred ETH to this wallet. I made a swap and wanted to send the remaining ETH to another wallet.

On another wallet, I also connected the Optmistic Ethereum network.

I sent 0.7 ETH on the Optimistic Ethereum network.

The funds did not come. I'm trying to check the information on optimistic.io.
But on I see "404 Page not found".

How can I solve this problem?

PS: 
Tx: 0x10443ddd01feab13e044efe4550622ee73a7b300a6b60f54a69f55a3af46a36d
From: 0x0b013b2F5C67522a00e38358E88Fc745a2c0e039
To: 0xF57dBdDF5268C6F896DeD614a44856b1F78E4331

<img width="311" alt="Снимок экрана 2021-07-23 в 17 08 39" src="https://user-images.githubusercontent.com/87864768/126794221-281098e5-748e-4364-a34b-8ef6ec7a7c3a.png">
<img width="1218" alt="Снимок экрана 2021-07-23 в 17 08 54" src="https://user-images.githubusercontent.com/87864768/126794228-a172c996-4512-4fd9-81de-209a12014afd.png">

**Comment by smartcontracts** [comment]
You should be able to see your transaction here: https://optimistic.etherscan.io/tx/0x10443ddd01feab13e044efe4550622ee73a7b300a6b60f54a69f55a3af46a36d

**Comment by smartcontracts** [comment]
I hope that gives you the information you need. I'm going to close this issue since it's not related to the community hub!
