### ISSUE TITLE
funds from optimistiс didn't come to the etherium mainnet

### ISSUE THREAD

**Issue by edward846** [ethereum-optimism/community-hub#136]
I decided to test L2 optimism about 2 weeks ago. I had 100$ in ethereum and I sent them to the liquidity of 50$ dai / 50$ ethereum. Funds were lying there for about a week and I decided to close it. After that, I went to the optimistic gateway and ordered the withdraw. They wrote to me that the media will come on July 29. today is 31, but I still can't see them anywhere. I have paid all the commissions and they are marked as successful on the etherscan and optimism scan. Please tell me how to solve this problem
![1](https://user-images.githubusercontent.com/83539724/127736248-39e1237f-c9f6-4919-945c-b5fd2f44b224.png)
![2](https://user-images.githubusercontent.com/83539724/127736249-5bdb8db4-800a-4bbb-8c18-58b9104f9eb3.png)

**Comment by smartcontracts** [comment]
Can you link your address on opti etherscan?

**Comment by edward846** [comment]
> Can you link your address on opti etherscan?

yes. i can/ this my address  0xE53fB7989aD637F7A674e8DB71e85cAB60607183

**Comment by smartcontracts** [comment]
You need to send your withdrawal to L1. You can use this webpage to do that: https://optimistic.etherscan.io/address/0xE53fB7989aD637F7A674e8DB71e85cAB60607183#withdrawaltxs

Click on the "ready to relay" button.

Check out this tutorial for more detailed instructions: https://community.optimism.io/docs/users/gateway.html#withdrawing-back-to-l1

**Comment by edward846** [comment]
> You need to send your withdrawal to L1 manually. You can use this webpage to do that: https://optimistic.etherscan.io/address/0xE53fB7989aD637F7A674e8DB71e85cAB60607183#withdrawaltxs
> 
> Click on the "ready to relay" button.
> 
> Check out this tutorial for more detailed instructions: https://community.optimism.io/docs/users/gateway.html#withdrawing-back-to-l1
Thanks!

**Comment by smartcontracts** [comment]
Closing this unless there are other issues. Hope it goes well!
