### ISSUE TITLE
Withdraw not in Mainnet after 7 days and 23 hours

### ISSUE THREAD

**Issue by MarkEugling** [ethereum-optimism/community-hub#146]
Hi,

I am unaware how to check the status of a withdraw from optimistic to mainnet.  The transaction hash shows that the withdraw was successful 7 days and 23 hours ago.  So I just want to check and make sure nothing is wrong with my withdrawl.

https://optimistic.etherscan.io/tx/0x5cc36850b70c72125338ad59ed05a3db153b36e893320a4eb9e726277f4e0b99

**Comment by elenadimitrova** [comment]
The L2 transaction initiating the withdrawal was successful however you need to relay it to L1, see documentation here https://community.optimism.io/docs/users/gateway.html#withdrawing-back-to-l1 specifically point 13 where you need to relay the transaction here https://optimistic.etherscan.io/messagerelayer?search=0x5cc36850b70c72125338ad59ed05a3db153b36e893320a4eb9e726277f4e0b99

Reopen if any issues.

**Comment by MarkEugling** [comment]
This is perfect, thank you!
