### ISSUE TITLE
Deposit a token from L1 to L2

### ISSUE THREAD

**Issue by anjubora** [ethereum-optimism/community-hub#152]
To deposit the ERC721 token I am using the OVM_CrossDomainEnabled  bridge contract.
But while deposit it is giving this error :
ERROR : VM Exception while processing transaction revert.\

**Comment by qbzzt** [comment]
Have you tried the directions at https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-standard-token?

**Comment by anjubora** [comment]
The token is the ERC721 token.
 https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-standard-token.This link is specific to ERC20.
I am using this https://github.com/ethereum-optimism/contracts/pull/325 as a reference.

**Comment by elenadimitrova** [comment]
The standard bridge currently does **not** support ERC721 tokens. Note that the reference repository you are pointing to is archived.

**Comment by anjubora** [comment]
@elenadimitrova Is there any way to deposit and withdrawal of ERC721 token from Layer1 to layer2 or vice versa?

**Comment by elenadimitrova** [comment]
@anjubora not via the standard bridge. We will be looking to implement that but tbh it is not a high priority in the backlog atm. You can design a custom bridge for that if you really wanted to.

**Comment by platocrat** [comment]
hi @anjubora, myself and @fracek starting working on implementing ERC721 on the standard bridge. 

You are more than welcome to look at our PR, https://github.com/ethereum-optimism/optimism/pull/1313, for inspiration on how to add ERC721 to the standard bridge or work on the PR together with us 😃
