### ISSUE TITLE
trouble pulling funds from optimism back to mainnet.

### ISSUE THREAD

**Issue by De-Fi-Antz** [ethereum-optimism/community-hub#154]
We were investigating optimism. We sent 0.3 ETH from mainnet to optimism (this worked). Then we used uniswap on optimism to buy and pool some USDT (this worked). Then we converted back to ETH on optimism (this worked). Then we tried to send the remaining funds back to ETH mainnet (0.2526 ETH) - and that got half way thru and failed. We waited the week and got to this point https://optimistic.etherscan.io/messagerelayer?search=0x26483f3317376ca1deab14cf4641df675497ec5f4d334f8911b2a2f37e28ea41 

But each time we hit execute it just spins some blue squares. We tried a few times over the last couple of days. We tried having metamask network on mainnet and on optimism. But we get no further then this. Any ideas?

**Comment by elenadimitrova** [comment]
Thanks for reporting this! There was indeed an issue with the relayer which should now be fixed. I can see the tx was successfully relayed. Please reopen if a similar issue occurs.

**Comment by De-Fi-Antz** [comment]
Thanks for looking into this.
