### ISSUE TITLE
Check balance of a L2 smart contract from L1

### ISSUE THREAD

**Issue by viktor-settlemint** [ethereum-optimism/community-hub#163]
**Describe the bug**
Hello team, I tried to look at your following documentation https://community.optimism.io/docs/developers/bridge/messaging.html, I basically tried to follow the same setup in order to **check the balance of a contract on L2 from L1.**
I then did the following simple smart contracts, which I want to deploy on Kovan:

```
pragma solidity 0.7.6;
pragma experimental ABIEncoderV2;

import { OVM_L1CrossDomainMessenger } from "@eth-optimism/contracts/OVM/bridge/messaging/OVM_L1CrossDomainMessenger.sol";

// And pretend this is on L1
contract Bank is OVM_L1CrossDomainMessenger {
    
    address public ovmL1CrossDomainMessenger;
    
    constructor(
        address _ovmL1CrossDomainMessenger
    ) {
        ovmL1CrossDomainMessenger = _ovmL1CrossDomainMessenger;
    }
    
    function balanceL2(address myOptimisticContractAddress) public {
        uint256 balance;
        sendMessage(
            myOptimisticContractAddress,
            abi.encodeWithSignature(
                "balance()"
            ),
            1000000
        );
    }
}
```

**To Reproduce**
If I try to compile it on Remix I have the following error message: 
`not found @openzeppelin/contracts-upgradeable/utils/ReentrancyGuardUpgradeable.sol
`

And if I do it on Remix:

```
  const Bank = await hre.ethers.getContractFactory("Bank");
  const bank = await Bank.deploy('0x4361d0F75A0186C05f971c566dC6bEa5957483fD');
  const balanceL2 = await bank.balanceL2(l1Wallet.address);
```

then I have the following error message:

`Error: Transaction reverted: function call to a non-contract account
`

**Expected behavior**
I just would like to receive the balance of the smart contract

Thanks for the help and sorry for the broad question, I am new to optimism

**Comment by qbzzt** [comment]
@elenadimitrova , can you please take this?

**Comment by elenadimitrova** [comment]
@viktor-settlemint you cannot do this from a contract in a synchronous manner. This tutorial might be more useful for you: https://github.com/ethereum-optimism/optimism-tutorial/tree/main/l1-l2-deposit-withdrawal
There we deploy 2 different ERC20s to L1 and L2, transfer token between them and query the amounts on each layer in the [example.js script](https://github.com/ethereum-optimism/optimism-tutorial/blob/main/l1-l2-deposit-withdrawal/scripts/example.js). Is this clearer?
