### ISSUE TITLE
Will optimism be decentralized?

### ISSUE THREAD

**Issue by vindberg** [ethereum-optimism/community-hub#176]
Im trying to understand the nature of optimism. Is it correct that only one "Sequencer" is needed to run an optimism network? If yes, will that sequencer change periodically? Or is trust not need for the safety of the network but only for its execution?

Are there two solutions if the sequencer stops/are evil:

1. We will always be able to setup another sequencer (by governance vote?) and start the network up again?
2. We can always get our eth back into Ethereum?

Thanks for any clarifications.

**Comment by qbzzt** [comment]
It will be decentralized eventually.
