### ISSUE TITLE
An error occurred while interacting

### ISSUE THREAD

**Issue by Zyx51940930** [ethereum-optimism/community-hub#184]
![image](https://user-images.githubusercontent.com/80514062/132973485-f26e272a-572c-4ee0-96cd-541d6708e41f.png)
I sent an amount of ETH to myself, and then I can't transfer and trade normally. How to solve this situation?
I can't view him in the blockchain browser.Transaction hash not found
my address
0xE1faf9A2921566c04DF67696D8a424ae90c2960b

**Comment by yxw0206** [comment]
我也遇到同样问题了，兄弟，解决了告知一下，谢谢。V：UULX888

**Comment by qbzzt** [comment]
Can you please ask in our support channel on Discord (https://discord.gg/sdh9qkJX)?
