### ISSUE TITLE
Docs: Confusing description of encoding sequencer transaction costs

### ISSUE THREAD

**Issue by jet86** [ethereum-optimism/community-hub#189]
The [Gas Costs on L2](https://community.optimism.io/docs/developers/fees.html) ([GitHub source](https://github.com/ethereum-optimism/community-hub/blob/main/src/docs/developers/fees.md)) section **Encoding Sequencer transaction costs** under **Transaction fees on L2** has a confusing entry as follows:

```text
              (tx_size * d_price) + (exec_gas * exec_price)
gas_limit  =  ---------------------------------------------
                                gas_price
```

It is unclear what the line or the `gas_price` are intended to convey in this calculation. Looking at the actual code and code comments (mainly [EstimateGas](https://github.com/ethereum-optimism/optimism/blob/develop/l2geth/internal/ethapi/api.go#L1076), [DoEstimateGas](https://github.com/ethereum-optimism/optimism/blob/develop/l2geth/internal/ethapi/api.go#L968), and [EncodeTxGasLimit](https://github.com/ethereum-optimism/optimism/blob/develop/l2geth/rollup/fees/rollup_fee.go#L72)), it seems that `gas_limit` includes the entire user fee, and therefore should simply be the same as the `total_cost` entry in the preceding section.

Please let me know if I have missed something obvious here.

**Comment by qbzzt** [comment]
> It is unclear what the line or the `gas_price` are intended to convey in this calculation.

The line is division, and `gas_price` is the denominator. Maybe I should make that clearer, but we're going to retire this document soon anyway (in OVM 2.0 it has been redone, see https://community.optimism.io/docs/developers/l2/new-fees.html).
