### ISSUE TITLE
Withdraw and for more than 7 days, still haven't received my main net ether.

### ISSUE THREAD

**Issue by Duchess16** [ethereum-optimism/community-hub#195]
I have not received my ether more than 7 days after.

**Comment by qbzzt** [comment]
Have you finalized the withdrawal?

**Comment by Duchess16** [comment]
I think i did. Or how is it done?

**Comment by qbzzt** [comment]
Sorry, I forgot to include the link. https://community.optimism.io/docs/users/gateway.html#finalizing-the-withdrawal

**Comment by Duchess16** [comment]
I'm trying to do the final withdrawal, its not working. It just get stucks at execution.
![Screenshot_2021-09-20-22-34-47-271_io metamask](https://user-images.githubusercontent.com/76067114/134079092-a1ec3eba-75ce-4d23-b040-622e80ad180d.jpg)

**Comment by qbzzt** [comment]
Can you please post this in our Discord on the #user-support channel? Sorry, but that way more people will see it.

https://discord.gg/xqfjPXxq
