### ISSUE TITLE
Typo In FAQ "Why is there a delay when moving assets from Optimistic Ethereum to Ethereum?"

### ISSUE THREAD

**Issue by KGJason** [ethereum-optimism/community-hub#2]
Typo in the last sentence of the FAQ:

**Why is there a delay when moving assets from Optimistic Ethereum to Ethereum?**
> As a result, we __seem__ a delay of about a week when moving assets back onto Ethereum.

**Comment by maurelian** [comment]
Good catch, thank you! Fixed here: #3

**Comment by lukem232** [comment]
Is it possible to retrieve regular eth that is sent to optimism wallet by accident
