### ISSUE TITLE
Add OE system “roles” to FAQs

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/community-hub#22]
Add these FAQs in docs and in discord:

1)    Who runs the sequencers?
2)    Can I run a sequencer?
3)    Who runs fraud provers?
4)    Can I run a fraud prover?
5)    What are the incentives to running sequencers and fraud provers?

See https://discord.com/channels/667044843901681675/667044844366987296/815064237972914176 for reference

In addition, add a description of each role, explaining what their purpose is in OE.

**Comment by platocrat** [comment]
@TransmissionsDev My consolidation of your replied in discord:

-------------------

## Answers

1. Only authorized parties rn but eventually will be given permission via MEVA auction
2. Long term yes but u will have to win an auction
3. Anyone
4. Yes!
5. Sequencer gets ten fees, fraud provers get the bond of a lying proposer when they prove fraud.


## Descriptions of roles

### Sequencers
* Sequencer is chosen via a MEVA auction. 
* Sequencer is a special user who gets the right to order transactions. 
* Users can send their transactions to the sequencer and get a signed confirmation for instant inclusion. 
* The sequencer submits a bundle of txs they have received every couple of minutes. 
* They get tx fees from the transactions they bundle
### Bonded Proposers
* A bonded proposer is usually the sequencer 
* Anyone can become a Bonded Proposer by putting up some money as a bond, but the sequencer gets first priority.
* Bonded proposer looks at those bundles of txs and computes the actual ethereum state trie from the bundle and publishes the merkle root onto L1
### Verifiers
* Anyone can be a verifier
* Verifiers also compute the actual state but are not looking to propose, they are looking to catch a bonded proposer who has lied about the correct state. 
*  If the verifier finds that a bonded proposer lied, they submit a tx to the L1 chain to have that transaction they believe is fraudulent computed and if the proposer was indeed lying, their bond (money they put up front) is taken away and given to the verifier(edited)
### Nodes
* Anyone can be a node
* Anyone can become a node and recompute the state themselves (just like you would on L1)

**Comment by TransmissionsDev** [comment]
Awesome yeah this all looks pretty good!

Couple of nitpicks:

- "Anyone can be a node" is repeated twice in the Nodes section

> their bond (money they put up front) is taken away and given to the verifier(edited)
- Remove the (edited) heh
- And only a portion of the bond is given to the verifier. Some of it is burned in case the proposer was himself also the verifier.

- Maybe mention that if the sequencer does not include a tx they signed and confirmed, a user can submit that signed confirmation to slash the sequencer's bond

Otherwise this looks pretty good, make it a PR?

**Comment by platocrat** [comment]
this is quite stale and I believe that this documentation should get added with incremental smaller PRs.
I'll be closing this for now, but it will get solved as we expand the protocol and to;dr documentation.
