### ISSUE TITLE
translate user docs to SChinese

### ISSUE THREAD

**Issue by imtipi** [ethereum-optimism/community-hub#222]
i want to translate user docs part to Chinese,how can i do it

**Comment by uniyj** [comment]
Happy to help, including reviews etc., if useful. I help look after the Chinese and Japanese translations for Uniswap UI (on Crowdin).

**Comment by imtipi** [comment]
> Do you volunteer to translate them and want us to put the translated versions on our web site?

yes, do it as a volunteer. and translate the user docs. and you can put it on optimism website(I think it is community.optimism.io)

**Comment by silentwars** [comment]
我很乐意帮忙，但不知道大家进展到什么程度了。

**Comment by silentwars** [comment]
I am willing to help, but I don't know how far you have progressed.

**Comment by silentwars** [comment]
I am very willing to help, but I don't know how far your translation is.

**Comment by lukassim** [comment]
@smartcontracts If you'd like some help getting set up with a localization tool to handle the translation workflow and file management for you, let me know, would love to share how we approach this.

**Comment by Felix471** [comment]
> @smartcontracts If you'd like some help getting set up with a localization tool to handle the translation workflow and file management for you, let me know, would love to share how we approach this.

Hi there, I submitted a new issue about Japanese translation and I would appreciate it if you can help me in setting up localization tools and file management, and something like that. #281
