### ISSUE TITLE
L1 <-> L2 Token Bridge

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/community-hub#24]
## Questions to be answered
* Does Optimism offer an L1 <-> L2 token bridge?
    * If not, who does?
* How does such a token bridge work?
    * Possible follow-up:  How do I use a token bridge as a user?
* What are gas fees like when using a bridge?
* Where can I learn about more token bridges to/from Optimism?

**Comment by TransmissionsDev** [comment]
Waiting for the spec to stabilize a bit. @dmihal is working on a modified implementation so I want to see what sticks first

**Comment by K-Ho** [comment]
We now have this standard deposit/withdrawal example that allows deploying of an L1<>L2 token bridge to a local network: https://github.com/ethereum-optimism/optimism-tutorial/tree/deposit-withdrawal

**Comment by platocrat** [comment]
Will add that in!

**Comment by krivochenko** [comment]
> https://github.com/ethereum-optimism/optimism-tutorial/tree/deposit-withdrawal

Sorry, I need this page, but it not found.

**Comment by qbzzt** [comment]
I apologize - it's now at https://github.com/ethereum-optimism/optimism-tutorial/tree/main/l1-l2-deposit-withdrawal. I will update the link.

**Comment by krivochenko** [comment]
I find it here
