### ISSUE TITLE
Add a protocol changelog page to the protocol docs

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/community-hub#264]
I'm going to remove the changeset from the developer docs, but I think it makes sense to create a new "protocol changelog" page where we can put changesets going forward. Will give people a history of how the protocol worked.

**Comment by elenadimitrova** [comment]
By protocol docs do you mean the optimistic-specs repo content? If so the change-log should go in there.

**Comment by smartcontracts** [comment]
Hmmm yeah, I guess so. I liked the idea of an abridged public-facing changelog for each release that could live in the community hub. But if you feel this isn't the right place for it, that's fine.

**Comment by Nicca42** [comment]
Related to #337 closing.
