### ISSUE TITLE
Remove mentions of whitelist

### ISSUE THREAD

**Issue by Nicca42** [ethereum-optimism/community-hub#284]
Remove all mentions of the whitelist from the docs. Replace with support form link.

**Comment by qbzzt** [comment]
It's at [this branch](https://github.com/ethereum-optimism/community-hub/tree/20211207-bye-bye-white-list). I left one mention, in the networks page, which explicitly states we removed it. I figured this would be much better than disappearing it without a trace and having people who knew about it wonder what had happened.
