### ISSUE TITLE
Typo in CrossDomainMessenger documentation

### ISSUE THREAD

**Issue by zhaochengpro** [ethereum-optimism/community-hub#289]
![image](https://user-images.githubusercontent.com/38267662/145956607-9d358ae2-50c0-466d-9038-08f93791fe8f.png)
 There is a docs issue. Should modify 
```
abi.encodeWithSignature(
      "doSomething(uint256)",
      myFunctionParam
),

```
to
```
abi.encodeWithSignature(
      "doSomething()",
      myFunctionParam
),
```

**Comment by smartcontracts** [comment]
Typos can be found here:
1. https://github.com/ethereum-optimism/community-hub/blob/009c3c4cded147bc8ee77a25ed8382d5e51f51c1/src/docs/developers/bridge/messaging.md?plain=1#L51
2. https://github.com/ethereum-optimism/community-hub/blob/009c3c4cded147bc8ee77a25ed8382d5e51f51c1/src/docs/developers/bridge/messaging.md?plain=1#L111

Same typo in both locations

**Comment by smartcontracts** [comment]
Super easy issue for a first-time contributor :-)

**Comment by LeifuChen** [comment]
> Super easy issue for a first-time contributor :-)

I just need to create a pull request to fix the typo, right? I can have a try.
