### ISSUE TITLE
Remove OVM 1.0 from the Running a development node guide

### ISSUE THREAD

**Issue by Nicca42** [ethereum-optimism/community-hub#295]
In the "Running a Development Node" tutorial, there is reference to an OVM 1.0 docker image. This is no longer relevant and causes confusion. Remove reference to OVM 1.0 in [this page](https://community.optimism.io/docs/developers/l2/dev-node.html). 

Once removed, please follow the tutorial locally to make sure that it is correct and up to date.

**Comment by LeifuChen** [comment]
I will start working on it.
