### ISSUE TITLE
Demo how to use "messaging" contracts in dev docs

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/community-hub#32]

**Comment by smartcontracts** [comment]
Seems like this can be closed now. Let me know if you think otherwise.

**Comment by platocrat** [comment]
I think no, but I also spoke with Kevin this morning about adding a “how-to” user page for how L1 <> L2 messaging works

**Comment by platocrat** [comment]
^so, the PR that fixes this should also add a user guide on messaging

**Comment by platocrat** [comment]
This will be closed by [ethereum-optimism/l1-l2-deposit-withdrawal](https://github.com/ethereum-optimism/l1-l2-deposit-withdrawal)
