### ISSUE TITLE
Broken image on a guide page

### ISSUE THREAD

**Issue by snario** [ethereum-optimism/community-hub#333]
1. Go to https://community.optimism.io/docs/guides/wallet-dev/#
2. See some images are not rendering, they 404, such as this one https://community.optimism.io/assets/img/chains-metamask.0571d24e.png

**Comment by qbzzt** [comment]
I couldn't find the string `24e.png` anywhere in the source file view-source:https://community.optimism.io/docs/guides/wallet-dev/# .

**Comment by smartcontracts** [comment]
@snario you may be looking at a cached version of the page. We just updated that wallet dev page a few days ago and removed those images.

**Comment by Nicca42** [comment]
Closing this, cached issue no longer applies.
