### ISSUE TITLE
Local RPC url and chainID are incorrect when creating custom network on MetaMask

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/community-hub#34]
# Summary
Using `optimism-integration` to create a custom network on MetaMask does _not_ work as expected (as explained in the developer docs).  

## Explanation of issue
In the developer docs, there is a [section](http://community.optimism.io/docs/developers/integration.html#using-the-optimism-integration-repo) with steps to setup the `optimism-integration` repo. Here's a snapshot of the section I'm referring to:

<img width="649" alt="Screen Shot 2021-03-07 at 7 00 53 PM" src="https://user-images.githubusercontent.com/37757724/110261870-74106780-7f77-11eb-9932-7b72606d2042.png">

Once the containers are running, I tried to connect to either `localhost:9545` or `localhost:8545`, which the docs imply are available to connect. In MetaMask, I try creating a new custom network with the RPC url as `http://localhost:9545` and the chainID as `420`, but I receive this error instead:

<img width="359" alt="Screen Shot 2021-03-07 at 6 53 50 PM" src="https://user-images.githubusercontent.com/37757724/110261596-7920e700-7f76-11eb-81e3-ead2467feb6b.png">

## Steps to Reproduce
1. Follow the steps under the "[Using the `optimism-integration` Repo]"(http://community.optimism.io/docs/developers/integration.html#using-the-optimism-integration-repo) to spin up the complete L1/L2 dev environment, and leave the containers running
2. Try to create a new custom network in MetaMask, using `http://localhost:9545` as the "New RPC URL" and `420` as the "Chain ID".
3. Click "Save"
4. See the error shown above.

## Additional notes
After chatting with @maurelian, he suggested I use `http://0.0.0.0:9545`, however, when doing so, I get this more helpful error:

<img width="359" alt="Screen Shot 2021-03-07 at 6 55 59 PM" src="https://user-images.githubusercontent.com/37757724/110261680-c309cd00-7f76-11eb-8057-c88de74f812c.png">

Using that chainID, `31337` lets MetaMask create the custom network, no problem.

------
@kfichter Wondering if I'm doing something wrong or if there's something missing from the docs?

**Comment by smartcontracts** [comment]
Ah yeah this is a poor configuration in our defaults for L1 and L2. The L1 node runs on `0.0.0.0:9545` while the L2 node runs on `0.0.0.0:8545`. So you just need to connect to `0.0.0.0:8545` and it should work. Sorry, I know it's confusing. We need to change this ASAP.

**Comment by platocrat** [comment]
will continue the discussion in a PR
