### ISSUE TITLE
Add a link in the RPC page to the replica providers and their RPCs.

### ISSUE THREAD

**Issue by qbzzt** [ethereum-optimism/community-hub#341]
Modify: https://community.optimism.io/docs/developers/l2/json-rpc.html

**Comment by slicken** [comment]
Your link don't work

> Modify: https://community.optimism.io/docs/developers/l2/json-rpc.html

Link does not work

**Comment by qbzzt** [comment]
Yes, this is ancient and I've already done it - thank you for reminding me to close the issue.
