### ISSUE TITLE
Update to warm/cold storage gas costs

### ISSUE THREAD

**Issue by qbzzt** [ethereum-optimism/community-hub#346]
> This hardfork brings you warm/cold storage gas costs, an updated gas schedule that more closely matches mainnet

Is it identical to mainnet? If not, what are the differences? People reading "an updated gas schedule that more closely matches mainnet" will immediately ask this question.

**Comment by mslipper** [comment]
The hardfork includes the following EIPs:

- https://eips.ethereum.org/EIPS/eip-2929
- https://eips.ethereum.org/EIPS/eip-2565
- https://eips.ethereum.org/EIPS/eip-3529

There may still be unimplemented EIPs, but as far as each of these EIPs go the system will be identical to mainnet.
