### ISSUE TITLE
Guide for Oracles on Optimism 

### ISSUE THREAD

**Issue by Nicca42** [ethereum-optimism/community-hub#359]
Create a guide for using Oracles on optimism. 

Should cover:
- what an oracle is (high level, getting data on chain)

Then for each oracle
- what type of oracle they are (push prices on chain, prices on request, etc) with a very high level how it works
- How to use it 
- where to find resources about OP endpoints
- Link to their docs

**Comment by qbzzt** [comment]
Oracles to document:
- Chainlink
- UMA
- Band Protocol
