### ISSUE TITLE
Revert reasons on eth_sendRawTransaction

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/community-hub#36]
Make a note in the dev docs that revert reasons are not returned on eth_sendRawTransaction calls. you'll have to do an `eth_call` at that block height to get the revert reason

**Comment by platocrat** [comment]
> you'll have to perform a call - e.g. like this: https://github.com/Synthetixio/synthetix-cli/blob/2b23c10fd9ad1f80cbe34864ae60bd478d43c96e/src/utils/runTx.js#L30-L57

Any significant difference between that version and the newer one?:
https://github.com/Synthetixio/synthetix-cli/blob/165fb39ea9c4298d7193c1b7f169dfd95cc89a80/src/utils/runTx.js#L61-L72
