### ISSUE TITLE
404: Sequencing documentation 😔

### ISSUE THREAD

**Issue by andrewkmin** [ethereum-optimism/community-hub#377]
https://community.optimism.io/docs/protocol/sequencing/ is leading to a 404, and this link seems to rank pretty high SEO-wise as it's all that would come up when I would search for `optimism block sequencing` 😄

**Comment by bdresser** [comment]
thanks for flagging @andrewkmin – taking a look 👀

**Comment by qbzzt** [comment]
> https://community.optimism.io/docs/protocol/sequencing/ is leading to a 404, and this link seems to rank pretty high SEO-wise as it's all that would come up when I would search for `optimism block sequencing` 😄

Thank you for reporting this. We put a redirect there so it's working now.
