### ISSUE TITLE
Explain the need to deposit ETH to pay for fees

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/community-hub#39]
Our L1<>L2 docs don't currently explain that users will need to deposit ETH in order to pay for fees on L2: https://community.optimism.io/docs/developers/integration.html#bridging-l1-and-l2

We just need to add a brief explanation of the standard ETH bridge and the flow that users will need to take to be able to pay fees.

**Comment by platocrat** [comment]
Going to make a PR that addresses this and #24.
