### ISSUE TITLE
Add a native faucet into the facet page. 

### ISSUE THREAD

**Issue by Nicca42** [ethereum-optimism/community-hub#390]
Multiple users have struggled to use the available facets to get testing Ether. To fix this the following is being proposed: 
* [ ] Build an Optimism facet 
        * Should send you ETH 
        * Should send you some ERC20s
        * Should send you some ERC721s 
* [ ] Add the address input directly into the facet page so that when you land on the facet page the top thing on the page is an input field for your address
* [ ] Add a button to send funds to your address (initially this can trigger the paradigm facet, later this should be our own facet)
* [ ] Add a button for bulk Ether requests. Something like: "Need a lot of ETH? Apply here" that goes to a google form with a captcha (or a typeform)

**Comment by Nicca42** [comment]
This is not high priority, but should be done before the end of May.

**Comment by qbzzt** [comment]
We can close this. Between optimismfaucet.xyz for ETH and https://community.optimism.io/docs/guides/testing/#goerli-erc-20-testing-contracts for an ERC-20, it's almost done. 

Still need an ERC-721 faucet, I'll make a link on linear.
