### ISSUE TITLE
Centralize info on Optimism's public resources and repos. 

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/community-hub#4]
# Purpose
There's a lot of tedious questions I find that get repeatedly answered in the Discord server channels. So, I think there should be:
1. A compilation of all of Optimism's public resources that the team has shared across their blog. 
2. A short summary of each resource. 
3. Similarly, there should also be brief and higher-level descriptions for each of Optimism's GitHub repos. 

All 3 of these things should be contained within one page to serve as a "table of contents" for learning more about all things Optimism. 

> Note: If a user wants more detailed info, they can work through the resources, tutorials, and guides provided, or learn more about the core protocol itself and how to integrate the OVM into their apps, elsewhere in the documentation. 

### 1. General
* [Mainnet soft launch](https://medium.com/ethereum-optimism/mainnet-soft-launch-7cacc0143cd5) (Jan. 15th, 2021)

### 2. Guides and Tutorials
* [Scopelift 's Uniswap v2 OVM tutorial](https://hackmd.io/@scopelift/Hy853dTsP) (my personal favorite, since it's thorough) (October - December 2020)
* [Optimism's official introductory tutorial](http://community.optimism.io/tutorial/) (short and sweet) (Jan. 15, 2021)
* [Unofficial guide on deploying a custom Optimism rollup on Kovan](https://gist.github.com/miguelmota/973e62c8f3da0571fc2c469b65c54d71)

### 3. Protocol Readings
* [OVM Deep Dive, Medium post](https://medium.com/ethereum-optimism/ovm-deep-dive-a300d1085f52) (May 5th, 2020)
* [OVM/EVM differences](https://hackmd.io/Inuu-T_UTsSXnzGtrLR8gA)
* [OVM vs. EVM Incompatibilities](https://hackmd.io/Inuu-T_UTsSXnzGtrLR8gA#Constructor-Parameters-may-be-Unsafe)
* [How does Optimism's Rollup really work?](https://research.paradigm.xyz/optimism) by Georgios Konstantopoulos from Paradigm Research (a thorough read)
* [MEV Auction: Auctioning transaction ordering rights as a solution to Miner Extractable Value](https://ethresear.ch/t/mev-auction-auctioning-transaction-ordering-rights-as-a-solution-to-miner-extractable-value/6788)

### 3. Speaking engagements
* [From Scalable to Sustainable](https://www.youtube.com/watch?v=0hppV1IfILw&feature=youtu.be) by Karl Floersch at SustainWeb3
* [Optimistic Rollup](https://www.youtube.com/watch?v=97DU_YgNPgE&feature=youtu.be) by Karl Floersch at EDCON 2020
* [Optimism: Keeping Ethereum Half-Full](https://www.youtube.com/watch?v=eYeOW4ePgZE) by Kelvin Fichter at ETHOnline
* [ETH2 Data Availability and Rollups](https://www.youtube.com/watch?v=q42NZw6Gle0&feature=youtu.be) by Ben Jones at ETHOnline
* [Optimistic Podcast](https://blockcrunch.libsyn.com/is-plasma-dead-the-rise-of-optimistic-rollups-on-ethereum-kevin-ho-optimism-ep-97) by Kevin Ho on BlockCrunch

### 4. Tools
* [`smock`](https://github.com/ethereum-optimism/smock):  
  Smock is a hardhat plugin that allows you to mock the functionality of any smart contract with just a little bit of JavaScript. Smock's README on GitHub has thorough documentation.
   * [Community example of using Smock](https://soliditydeveloper.com/smock)
* [`ovm-toolchain`](https://github.com/ethereum-optimism/optimism-monorepo), i.e. Optimism Monorepo
* [Optimism's `contracts-v2`](https://github.com/ethereum-optimism/contracts-v2):
  Smart contracts that make up the L1 component of Optimism's ORU contruction.
* [Optimism Service Integration and Rapid Development](https://github.com/ethereum-optimism/optimism-integration):
  Intended to provide the ability to run a local Optimistic Ethereum environment including both L1 & L2 chains. This can be used to rapidly iterate over the many Optimism repositories and run integration tests.

## How this fits with the rest of the community hub's docs 
Since the above will serve as a higher-level table-of-contents, then the subsections of the "Protocol" and "Integration" can be left for advanced users that would either like to learn more about the technical details of the protocol, or learn how to integrate the OVM into their apps.

**Comment by maurelian** [comment]
Amazing! So, I understand correctly, the change would essentially be to add a new page that contains more or less exactly this content?

**Comment by platocrat** [comment]
Right. Some more text to include a summary of each.

**Comment by kfichter** [comment]
@platocrat This is fantastic. Do you want to make a draft PR adding this page to the site? I'd be down to hop on a call to walk you through it if you need any help.

**Comment by platocrat** [comment]
getting to work on the PR rn
