### ISSUE TITLE
False information in the docs?

### ISSUE THREAD

**Issue by john-light** [ethereum-optimism/community-hub#411]
It says on [L2 Beat](https://l2beat.com/projects/optimism/#withdrawals):
> Funds can be frozen if the centralized validator goes down. Users cannot produce blocks themselves and exiting the system requires new block production (CRITICAL) ([citation](https://etherscan.io/address/0xCd76de5C57004d47d0216ec7dAbd3c72D8c49057#code#F6#L71)).

This seems to me to contradict what is said in the [Optimism documentation](https://community.optimism.io/docs/how-optimism-works/#block-production):
> Alternatively, users can skip the sequencer entirely and submit their transactions directly to the CanonicalTransactionChain via an Ethereum transaction...  Even if the sequencer is actively censoring a user, the user can always continue to use Optimism and recover any funds through this mechanism.

To confirm: is the Sequencer the only entity that can submit a state root update? And therefore if the Sequencer is uncooperative, they can censor user transactions (including withdrawals to L1)?

**Comment by qbzzt** [comment]
The sequencer is the only entity that can submit a state root update. However, after a certain amount to time has passed, the only valid update is one that includes the transaction submitted on L1.

Right now we're still centralized so we could stop our entire blockchain to censor user transactions. We are working on decentralization, and once we achieve that anybody else could start a sequencer if we decide not to run ours for some reason.

**Comment by qbzzt** [comment]
I don't think it's worth updating because it's economically unfeasible. 

To censor a user we'd have to shut down our whole operation. Everybody involved will lose their reputation, our investors would sue us (not just the company, but all the directors and executives individually), etc.

**Comment by smartcontracts** [comment]
> I don't think it's worth updating because it's economically unfeasible.
> 
> To censor a user we'd have to shut down our whole operation. Everybody involved will lose their reputation, our investors would sue us (not just the company, but all the directors and executives individually), etc.

I think we should update it. The statement being made is "if the sequencer is actively censoring" so the response of "we won't censor" is orthogonal.

**Comment by smartcontracts** [comment]
@john-light please let me know if the note [here](https://github.com/ethereum-optimism/community-hub/pull/415/files#diff-a2377cc33b3952a9fb6ec3d989f68cb9c0f1334fdc6956ec290d634c8d6c82a2R136-R141) seems sufficient

**Comment by john-light** [comment]
@smartcontracts the note you linked to plus the update [on line 131](https://github.com/ethereum-optimism/community-hub/pull/415/files#diff-a2377cc33b3952a9fb6ec3d989f68cb9c0f1334fdc6956ec290d634c8d6c82a2R131) together are sufficient to close this issue, thanks.

Something you may or may not know: if you put `Closes #411` in the description of your PR then it will automatically close this issue when the PR is merged.
