### ISSUE TITLE
dead links in attestation docs

### ISSUE THREAD

**Issue by Michael-Vander-Meiden** [ethereum-optimism/community-hub#568]
Both of these example interface links are dead.

https://github.com/ethereum-optimism/community-hub/blob/36ecf888d793385abe711dd9e052736efb994157/src/docs/governance/attestation-station.md?plain=1#L54-L55

**Comment by smartcontracts** [comment]
Both seem to work for me

**Comment by Michael-Vander-Meiden** [comment]
I just checked again, every single other external link worked for me except those two.

After turning on a VPN, the links in question worked fine. Might be a local thing, closing the issue for now 👍
