### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by estensen** [ethereum-optimism/community-hub#57]
**Describe the bug**
Some links returns 404

**To Reproduce**
1. Go to 'optimism.io'
2. Click on 'Tutorial'
3. See error 404 and 'Not secure' warning

Same with http://community.optimism.io/docs/protocol/tldr.html

**Comment by platocrat** [comment]
Thanks a lot for this!
We're working on fixing this issue right now.

**Comment by platocrat** [comment]
Fixed with #64
