### ISSUE TITLE
Deposit/Withdrawal Standard Docs

### ISSUE THREAD

**Issue by TransmissionsDev** [ethereum-optimism/community-hub#6]
https://github.com/ethereum-optimism/contracts-v2/pull/219

https://github.com/ethereum-optimism/contracts-v2/pull/222

**Comment by platocrat** [comment]
@kfichter @maurelian  Just curious, Maurelian mentioned in the last stream that there should be more "good first issue" labels. Were the labels for denoting what content to add to the docs, or are they also needed across other repos?

**Comment by maurelian** [comment]
Either/both!

**Comment by platocrat** [comment]
This will be closed by [ethereum-optimism/l1-l2-deposit-withdrawal](https://github.com/ethereum-optimism/l1-l2-deposit-withdrawal)
