### ISSUE TITLE
Refine the integration docs

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/community-hub#8]
## Description

Improve the integration docs using the output from #8. 

We can also make some minor improvements to formatting: 
- It might help to add a couple [custom containers](https://vuepress.vuejs.org/guide/markdown.html#custom-containers) to make important high level information more prominent (also don't over do it)
- Fix the links in section 3 to hide the long URLs using the `[text](link)` syntax

**Comment by platocrat** [comment]
should add a section that covers L1 <> L2 communication:
https://discord.com/channels/667044843901681675/803723425054851083/812381641098919986

**Comment by platocrat** [comment]
> should add a section that covers L1 <> L2 communication:
> https://discord.com/channels/667044843901681675/803723425054851083/812381641098919986

this has been covered in #11

**Comment by platocrat** [comment]
Closing this after Kelvin's recent page additions. Shifted to adding specific issues now
