### ISSUE TITLE
Running a node without Docker docs requires more detail about l1kind

### ISSUE THREAD

**Issue by imtipi** [ethereum-optimism/community-hub#860]
in "Running a node without Docker", the op-node part didn't provide enough details of l1kind, so users will be confused if they want to use other rpc providers.
![image](https://github.com/ethereum-optimism/community-hub/assets/27230181/a04bd326-8af7-4039-a48a-80b9a801238e)
suggestion: use the description from https://github.com/smartcontracts/simple-optimism-node#op_node__rpc_type

> The L1KIND environment variable tells the op-node component of the Bedrock node what sort of RPC it is connected to. When this variable is configured properly op-node can execute more efficiently by using special RPC endpoints that some RPC providers have and others may not. The available options for this variable are alchemy, quicknode, infura, parity, nethermind, debug_geth, erigon, basic, and any. The default is basic.

**Comment by sbvegan** [comment]
Thanks for your feedback this is fixed in #880
