### ISSUE TITLE
DevEx workflow improvement 

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/community-hub#88]
**Description**
@TransmissionsDev suggested that docs should more _clearly_ advise that your tests work on jsvm and local l2geth before testing against Kovan or in a CI.
It can also be more explicit that debugging first with the jsvm and local l2geth is far easier than against Kovan or in a CI.

There should be more emphasis on this suggestion.

**Motivation**
Quoting @TransmissionsDev from discord:
"That way all the existing tooling will work and you get nice revert messages.
If you use `xDomainMessenger` and other stuff, you are going to have to mock that out but it is worth it."

@TransmissionsDev could you expand on what exactly to mock and give an example?

Additional motivation:
* Improve our documentation by being _explicit_ and _concise_
* Incorporate user and community member feedback to improve documentation and DevEx

**Estimated effort and complexity**
* Effort: 2-4
* Complexity: 0

**Tags to related packages**
* `l2geth`

## Update
Include content in docs that addresses t11s' reply below:
> > It can also be more explicit that debugging first with the jsvm and local l2geth is far easier than against Kovan or in a CI.

> Mainly was emphasizing that debugging with jsvm specifically is much easier than l2geth. l2geth doesn't give revert messages, will only show gas estimations for l2 contracts with `solidity-gas-reporter` (even if you have l1 contracts you interact with in your tests) and is incompatible with `solidity-coverage`. You also can't use hardhat's `console.sol` with l2geth of course.

**Comment by TransmissionsDev** [comment]
> could you expand on what exactly to mock and give an example?

Basically any Optimism precompiles that you use when running your tests on l2geth (OVM_ETH, cross domain messengers, etc, etc) need to be manually deployed in the jsvm (where as on L2 geth they are assigned addresses at geth startup and useable without setup in tests). 

However some of those contracts are pretty complex to setup manually on L1 and require external relayers, etc so for some I would recommend writing a custom "mock" version.

**Comment by TransmissionsDev** [comment]
> It can also be more explicit that debugging first with the jsvm and local l2geth is far easier than against Kovan or in a CI.

Mainly was emphasizing that debugging with jsvm specifically is much easier than l2geth. l2geth doesn't give revert messages, will only show gas estimations for l2 contracts with `solidity-gas-reporter` (even if you have l1 contracts you interact with in your tests) and is incompatible with `solidity-coverage`.

**Comment by platocrat** [comment]
> Contracts can interact with this "cross domain messenger" with the same interface as is given by the l2geth precompile but the mock simplifies relaying the message (and doesn't actually do any "cross domain" calls as everything is happening in the jsvm)

Sorry, I was being a numpty and didn't realize I was overlooking the cross-domain messaging 😅.

> l2geth doesn't give revert messages, will only show gas estimations for l2 contracts with solidity-gas-reporter (even if you have l1 contracts you interact with in your tests) and is incompatible with `solidity-coverage`.

[ethereum-optimism/optimism/issues/474](https://github.com/ethereum-optimism/optimism/issues/474) should fix the issue with revert reasons not being returned when using l2geth.

**Comment by platocrat** [comment]
Per [this comment](https://github.com/ethereum-optimism/optimism/issues/474#issuecomment-828848407) on [ethereum-optimism/optimism/issues/474](https://github.com/ethereum-optimism/optimism/issues/474), the fix for revert reasons issue will not be pushed to production until 05/03/21

**Comment by platocrat** [comment]
Stale
