### ISSUE TITLE
Missing note for new `types-ovm`

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/community-hub#89]
**Describe the bug**
A recent fix in [ethereum-optimism/optimism#597](https://github.com/ethereum-optimism/optimism/pull/597) corrects an issue with typescript defs of one chain (L1) overwritting typescript defs of another chain (L2).

This change likely affects many users who have suffered from this issue or used their own way of getting around this issue.

**Expected behavior**
A note on the override for the TypeChain task to keep two type def paths for each artifacts, `types` and `types-ovm`.

**Additional context**
Advised by [ethereum-optimism/optimism#597](https://github.com/ethereum-optimism/optimism/pull/597#issuecomment-825904488)

**Comment by TransmissionsDev** [comment]
@platocrat To clarify, that change just changes how the `@eth-optimism/contracts` repo exports typechain defs. Projects which have L1 and L2 contracts will still face the same issue after that change is merged. I was suggesting to note in the docs that if users are annoyed by conflicting typechain defs they might want to add this to their hardhat config:

```js
import { task } from "hardhat/config";
import { TASK_COMPILE } from "hardhat/builtin-tasks/task-names";

task(TASK_COMPILE).setAction(async (args, hre: any, runSuper) => {
  if (hre.network.config.ovm && !hre.config.typechain.outDir.endsWith("-ovm")) {
    hre.config.typechain.outDir += "-ovm";
  }
  return runSuper(args);
});
```

**Comment by gakonst** [comment]
Per the latest change in https://github.com/ethereum-optimism/optimism/pull/597, the modification happens at the hardhat-ovm plugin, so should not be an issue.

**Comment by TransmissionsDev** [comment]
> Per the latest change in [ethereum-optimism/optimism#597](https://github.com/ethereum-optimism/optimism/pull/597), the modification happens at the hardhat-ovm plugin, so should not be required.

Great idea.
